import mysql.connector as mysql


db = mysql.connect(
   host='db-mysql-fra1-09136-do-user-7651996-0.b.db.ondigitalocean.com',
   port=25060,
   user='user1',
   password='AVNS_BIPHdghyp1-JLYypm-t',
   database='monstro'
)
cursor = db.cursor(dictionary=True)
cursor.execute('select * from students where id=1')
print(cursor.fetchone())
cursor.execute("insert into students (id, name, second_name, group_id) values (24, 'Kate', 'Tishevich', 100)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO books(id, title, taken_by_student_id) VALUES (15, 'The Her', 2433)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO `groups` (id, title, start_date, end_date)"
               " VALUES (15, 'Kotiki', '15-01-1999', '15-02-2023')")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO subjects (id, title) VALUES (20,'History')")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO subjects (id, title) VALUES (21,'Math')")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO subjects (id, title) VALUES (22,'OOP')")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO lessons (id, title, subject_id) VALUES (20,'History',20)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO lessons (id, title, subject_id) VALUES (21,'Math',22)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO lessons (id, title, subject_id) VALUES (22,'OOP',22)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO lessons (id, title, subject_id) VALUES (23,'History of Belarus',20)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO lessons (id, title, subject_id) VALUES (24,'Math 9-11',22)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO lessons (id, title, subject_id) VALUES (25,'OOP concept',22)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO lessons (id, title, subject_id) VALUES (25,'OOP concept',22)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO marks (id, student_id, lesson_id, mark) VALUES (20,2433,20,9)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO marks (id, student_id, lesson_id, mark) VALUES (20,2433,20,9)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO marks (id, student_id, lesson_id, mark) VALUES (21,2433,21,8)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO marks (id, student_id, lesson_id, mark) VALUES (22,2433,22,9)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO marks (id, student_id, lesson_id, mark) VALUES (23,2433,20,7)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO marks (id, student_id, lesson_id, mark) VALUES (24,2433,21,10)")
db.commit()
print(cursor.fetchone())
cursor.execute("INSERT INTO marks (id, student_id, lesson_id, mark) VALUES (25,2433,22,9)")
db.commit()
print(cursor.fetchone())
cursor.execute("select mark from marks where student_id = 2433")
print(cursor.fetchone())
cursor.execute("select title from books where taken_by_student_id = 2433")
print(cursor.fetchone())
cursor.execute("select * from marks join subjects on marks.id = subjects.id")
print(cursor.fetchone())
cursor.execute("select books.title book_title, marks.mark mark_number, lessons.title lesson_title,"
               " students.group_id group_number from students "
               "JOIN books on students.id = books.taken_by_student_id "
               "JOIN marks on students.id = marks.student_id"
               "JOIN lessons on marks.lesson_id = lessons.id"
               "JOIN `groups` on students.group_id = `groups`.id"
               "WHERE students.id = 2433")
print(cursor.fetchone())
db.close()
